services:
  coolify:
    environment:
      PUSHER_HOST: manage-realtime.forkedbrain.fyi
      PUSHER_PORT: "443"
    ports: !override
      - "127.0.0.1:8000:8080"
  soketi:
    ports: !override
      - "127.0.0.1:6001:6001"
      - "127.0.0.1:6002:6002"
