import { useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import { api, invalidate, useQuery } from '../lib/api';
import { EmptyState, ErrorState, Eyebrow, LoadingRows, ViewHead } from '../components/Desk';
import { compact, formatDate } from '../lib/desk';
import './ask.css';

export function Ask() {
  const [params] = useSearchParams();
  const topic = params.get('topic');
  const [question, setQuestion] = useState(topic ? `What are the strongest arguments and evidence about ${topic}?` : '');
  const [response, setResponse] = useState<any>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [historyQuery, setHistoryQuery] = useState('');
  const history = useQuery<{ history: any[] }>(`/ask/history?q=${encodeURIComponent(historyQuery)}&limit=50`, [historyQuery]);

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (question.trim().length < 3 || busy) return;
    setBusy(true);
    setError('');
    try {
      const next = await api('/ask', { method: 'POST', body: JSON.stringify({ question: question.trim() }) });
      setResponse(next);
      invalidate('/ask/history');
      history.refetch();
    } catch (requestError) {
      setError(requestError instanceof Error ? requestError.message : 'Hermes could not answer that question.');
    } finally {
      setBusy(false);
    }
  };

  const evidence = useMemo(() => response?.results ?? [], [response]);

  return (
    <section>
      <ViewHead title="Ask">
        Ask Mark's corpus a question. Answers are generated by Hermes and returned with the records used as evidence.
      </ViewHead>

      <div className="ask-layout">
        <div>
          <form className="ask-composer desk-card" onSubmit={submit}>
            <label htmlFor="ask-question">Question</label>
            <textarea id="ask-question" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="What changed in Aave governance, who argued for it, and which sources support that view?" />
            <div className="ask-composer-foot">
              <span>Hermes searches the unified private corpus first.</span>
              <button className="desk-button" type="submit" disabled={busy || question.trim().length < 3}>{busy ? 'Reviewing evidence' : 'Ask Satoshi'}</button>
            </div>
          </form>

          {error ? <div className="desk-error ask-error" role="alert"><strong>The answer failed.</strong><p>{error}</p></div> : null}
          {busy ? <div className="ask-working"><span /><p>Reading the most relevant stored records and assembling a cited answer.</p></div> : null}

          {response ? (
            <article className="ask-answer desk-card">
              <div className="ask-answer-head">
                <div><Eyebrow>Answer</Eyebrow><span>{response.evidence_count ?? evidence.length} evidence records</span></div>
                <button type="button" onClick={() => navigator.clipboard?.writeText(response.answer || response.message || '')}>Copy</button>
              </div>
              <div className="desk-markdown"><ReactMarkdown>{response.answer || response.message || ''}</ReactMarkdown></div>
              {evidence.length ? (
                <div className="ask-evidence">
                  <Eyebrow>Evidence used</Eyebrow>
                  {evidence.map((item: any) => {
                    const to = item.kind === 'source' ? `/source/${encodeURIComponent(item.canonical_id)}` : `/event/${item.canonical_id}`;
                    return <Link key={`${item.kind}-${item.canonical_id}`} to={to}><strong>{compact(item.title || item.canonical_id, 90)}</strong><span>{compact(item.snippet, 130)}</span></Link>;
                  })}
                </div>
              ) : null}
            </article>
          ) : null}
        </div>

        <aside className="ask-history desk-aside">
          <Eyebrow>Question history</Eyebrow>
          <input className="desk-input" type="search" value={historyQuery} onChange={(event) => setHistoryQuery(event.target.value)} placeholder="Search questions" aria-label="Search question history" />
          {history.loading && !history.data ? <LoadingRows rows={3} /> : null}
          {history.error ? <ErrorState error={history.error} retry={history.refetch} /> : null}
          {!history.loading && !history.error && !(history.data?.history?.length) ? <EmptyState title="No saved questions">Questions asked through this workspace will appear here.</EmptyState> : null}
          <div className="ask-history-list">
            {(history.data?.history ?? []).map((item) => (
              <button key={item.id} type="button" onClick={() => { setQuestion(item.question); setResponse({ answer: item.answer, results: item.evidence, evidence_count: item.evidence?.length, asked_at: item.asked_at }); }}>
                <strong>{compact(item.question, 92)}</strong>
                <span>{formatDate(item.asked_at)}</span>
              </button>
            ))}
          </div>
        </aside>
      </div>
    </section>
  );
}
