import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { api, useQuery } from '../lib/api';
import { Eyebrow, ViewHead } from '../components/Desk';
import './creator-bot.css';
const TONES=['analytical','contrarian','conversational']; const LENGTHS=['short','medium','long'];
export function CreatorBot({creator}:{creator:'Haseeb'|'Tarun'}){
 const sources=useQuery<{sources:unknown[]}>('/sources'); const [prompt,setPrompt]=useState(''); const [format,setFormat]=useState<'x_post'|'linkedin_post'>('x_post'); const [count,setCount]=useState('3'); const [tone,setTone]=useState(creator==='Haseeb'?'contrarian':'analytical'); const [length,setLength]=useState('medium'); const [customTone,setCustomTone]=useState(''); const [result,setResult]=useState<any>(null); const [feedback,setFeedback]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const run=async(revision='')=>{if(!prompt.trim()||busy)return;setBusy(true);setError('');try{const response=await api('/studio/drafts',{method:'POST',body:JSON.stringify({template_type:format,focus:`Write through the stored ${creator} creator reference. Tone: ${customTone.trim()||tone}. Length: ${length}. ${format==='x_post'?`Create ${count} distinct option${count==='1'?'':'s'}. `:''}${revision?`Revision notes: ${revision}. `:''}Subject: ${prompt.trim()}`,writing_lens:'creator_reference',source_ids:[]})});setResult(response);if(revision)setFeedback('')}catch(requestError){setError(requestError instanceof Error?requestError.message:'Generation failed')}finally{setBusy(false)}};
 const body=result?.body||'';
 return <section><ViewHead title={`${creator} bot`}/><div className="creator-bot-wrap"><div className="creator-bot-card"><Eyebrow>{creator==='Haseeb'?'What should he tweet about?':'What should he write about?'}</Eyebrow><textarea className="creator-prompt" rows={3} value={prompt} onChange={(event)=>setPrompt(event.target.value)} placeholder={creator==='Haseeb'?'e.g. why perp DEX fee compression is a distribution story, not an execution story':'e.g. why token governance is really a legitimacy problem, not a voting problem'}/><OptionRow label="Format" values={['tweet','blog post']} active={format==='x_post'?'tweet':'blog post'} setActive={(value)=>setFormat(value==='tweet'?'x_post':'linkedin_post')}/>{format==='x_post'?<OptionRow label="Tweets" values={['1','3','5']} active={count} setActive={setCount}/>:null}<OptionRow label="Tone" values={TONES} active={tone} setActive={setTone}/><label className="creator-custom"><span>Your own tone</span><textarea rows={2} value={customTone} onChange={(event)=>setCustomTone(event.target.value)} placeholder="Describe the voice you want in your own words"/></label><div className="creator-last-row"><OptionRow label="Length" values={LENGTHS} active={length} setActive={setLength}/><button type="button" onClick={()=>run()} disabled={busy||!prompt.trim()}>{busy?'Writing...':'Generate'}</button></div><p className="creator-count">{sources.data?.sources?.length??0} sources in corpus</p></div>
 <div className="creator-bot-card creator-output"><Eyebrow>Output</Eyebrow>{error?<p className="creator-error">{error}</p>:null}{!body&&!busy?<p className="creator-empty">Nothing generated yet. Write a prompt above and select Generate.</p>:null}{busy&&!body?<p className="creator-empty">Pulling voice from corpus...</p>:null}{body?<><div className="desk-markdown"><ReactMarkdown>{body}</ReactMarkdown></div><button className="creator-copy" type="button" onClick={()=>navigator.clipboard?.writeText(body)}>Copy</button><div className="creator-feedback"><Eyebrow>Feedback · suggest changes</Eyebrow><textarea rows={2} value={feedback} onChange={(event)=>setFeedback(event.target.value)} placeholder="e.g. make the second angle sharper and cut the final sentence"/><button type="button" onClick={()=>run(feedback.trim())} disabled={busy||!feedback.trim()}>{busy?'Revising...':'Revise'}</button></div></>:null}</div>
 {result?.citations?.length?<div className="creator-bot-card"><Eyebrow>Works cited · quotes &amp; inferences</Eyebrow>{result.citations.map((citation:any)=><div className="creator-citation" key={`${citation.kind}-${citation.id}`}><span>{citation.kind}</span><p>{citation.title}</p></div>)}</div>:null}</div></section>;
}
function OptionRow({label,values,active,setActive}:{label:string;values:string[];active:string;setActive:(value:string)=>void}){return <div className="creator-option-row"><span>{label}</span>{values.map((value)=><button key={value} type="button" className={active===value?'is-active':''} onClick={()=>setActive(value)}>{value}</button>)}</div>}
